### ISSUE TITLE
your C code is unoptimized

### ISSUE THREAD

**Issue by armandli** [jackeown/PythonIsNotSlow#1]
the reason your C code is slower is because numpy and cython compiles into vectorized instructions. try convert your C code with high performance linear algebra libraries such as Eigen and you'll see very similar performances between the C version and your cython version. (because they would be using the same thing)

**Comment by jackeown** [comment]
I fixed it. Basically by compiling using the -Os flag. Now the C code is indeed the fastest. I'm still happy with the performance of cython and numpy though.

With numpy, vectorizing your code helps because it ensures that the iterations are done with C and not with python, but with cython, as far as I know, there's no real vectorizing.

The numpy comparison probably still isn't fair since the numpy matrix multiplication probably uses a more efficient algorithm than my naive O(n^3) implementation in C and Cython. (I think the best known algorithm is around O(n^2.4) or so...)
